
let LAST=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>v==null?'–':new Intl.NumberFormat('tr-TR',{maximumFractionDigits:0}).format(v)+' TL';
const num=v=>v==null?'–':new Intl.NumberFormat('tr-TR',{maximumFractionDigits:1}).format(v);
const pct=v=>v==null?'–':num(v)+'%'; const rat=v=>v==null?'–':num(v)+'x';
function table(title,obj){return '<div class="notice" style="margin-bottom:8px"><b>'+title+'</b></div><table><tbody>'+Object.entries(obj||{}).map(([k,v])=>'<tr><td>'+esc(k)+'</td><td><b>'+money(v)+'</b></td></tr>').join('')+'</tbody></table>'}
function metric(label,value,sub){return '<div class="metric"><div class="label">'+esc(label)+'</div><div class="value">'+esc(value)+'</div><div class="sub">'+esc(sub||'')+'</div></div>'}
function setRing(v){$('scoreRing').style.setProperty('--score',Math.max(0,Math.min(100,v||0)));$('score').textContent=v==null?'–':Math.round(v)}
function waterfall(pl){const rows=[['Net satış',pl['Net sales'],false],['COGS',-pl['COGS'],true],['Brüt kâr',pl['Gross profit'],false],['Faaliyet gideri',-pl['Operating expenses'],true],['Faaliyet kârı',pl['Operating profit'],false],['Finansman',-pl['Finance costs'],true],['Vergi',-pl['Tax expense'],true],['Net kâr',pl['Net profit'],false]]; const max=Math.max(...rows.map(x=>Math.abs(x[1]||0)),1);$('waterfall').innerHTML=rows.map(r=>'<div class="wf '+(r[2]?'neg':'')+'"><div class="num">'+money(r[1]).replace(' TL','')+'</div><div class="col" style="height:'+Math.max(4,Math.abs(r[1]||0)/max*135)+'px"></div><div class="lab">'+esc(r[0])+'</div></div>').join('')}
function render(d){LAST=d;$('dashboard').classList.remove('hidden');const bp=d.business_partner,pl=d.statements.profit_and_loss,bs=d.statements.balance_sheet,k=d.statements.kpis;setRing(bp.health_score);$('healthLabel').textContent=bp.health_label;$('mSales').textContent=money(pl['Net sales']);$('mOp').textContent=money(pl['Operating profit']);$('mNet').textContent=money(pl['Net profit']);$('mDebt').textContent=money(k.net_debt);$('exec').innerHTML='<h3>'+esc(bp.executive_summary)+'</h3><p>'+esc(bp.methodology_note)+'</p>';
const kp=bp.executive_summary_engine?.key_points||[];$('keyPoints').innerHTML=kp.map(x=>'<div class="insight" style="margin-top:8px"><b>'+esc(x)+'</b></div>').join('');
const dq=d.quality?.advanced||{};$('dq').textContent=dq.score==null?'–':dq.score+'/100';$('dqStatus').textContent=dq.status||'–';const audit=bp.calculation_audit||{};$('audit').innerHTML='<div class="audit"><span class="dot '+(audit.status==='PASS'?'':'fail')+'"></span><b>Calculation Audit: '+esc(audit.status||'–')+'</b><span class="muted small">'+(audit.failed_count||0)+' failed checks</span></div>';
waterfall(pl);$('liquidity').innerHTML=[['Current Ratio',rat(k.current_ratio),'higher is better'],['Cash Ratio',rat(k.cash_ratio),'liquid cash / current liabilities'],['Debt / Equity',rat(k.debt_to_equity),'lower is generally safer'],['Debt / Assets',pct(bp.derived_metrics.debt_to_assets_pct),'financing intensity']].map(x=>metric(x[0],x[1],x[2])).join('');
const rr=bp.risk_ranking_engine?.ranked_risks||[];$('risks').innerHTML=rr.slice(0,8).map((r,i)=>'<div class="riskRow"><div class="rank">#'+r.rank+'</div><div><b>'+esc(r.title)+'</b><div class="riskScore">'+esc(r.category)+' · '+num(r.risk_score)+' / 100'+(r.estimated_exposure!=null?' · '+money(r.estimated_exposure):'')+'</div><div class="bar"><i style="width:'+Math.min(100,r.risk_score||0)+'%"></i></div></div><span class="tag '+String(r.risk_tier||'').toLowerCase()+'">'+esc(r.risk_tier)+'</span></div>').join('')||'<div class="notice">Öncelikli risk bulunmadı.</div>';
const rc=bp.root_cause_engine||{};$('rootCause').innerHTML=(rc.causal_chains||[]).map(c=>'<div class="insight" style="margin-bottom:10px"><h3>'+esc(c.title)+'</h3><div class="small muted">Primary driver: '+esc(c.primary_driver)+'</div><p>'+c.chain.map(esc).join(' → ')+'</p><div class="small muted">Causal status: '+esc(c.causal_status||'likely driver')+'</div></div>').join('')||'<div class="notice">Yeterli kök neden kanıtı yok.</div>';
const pq=bp.profit_quality_engine||{};$('profitQuality').innerHTML='<div class="grid2">'+metric('Gross Margin',pct(pq.gross_margin_pct),'')+metric('Operating Margin',pct(pq.operating_margin_pct),'')+metric('Net Margin',pct(pq.net_margin_pct),'')+metric('Finance Cost / Operating Profit',pct(pq.finance_cost_to_operating_profit_pct),'')+'</div>'+(pq.flags||[]).map(f=>'<div class="insight '+esc(f.severity)+'" style="margin-top:10px"><b>'+esc(f.title)+'</b><p>'+esc(f.detail)+'</p></div>').join('');
const sc=bp.scenario_engine?.scenarios||[];$('scenarios').innerHTML=sc.map(s=>'<div class="scenario"><h3>'+esc(s.name)+'</h3><div class="big">'+(s.cash_impact?money(s.cash_impact):s.profit_impact?money(s.profit_impact):s.debt_impact?money(s.debt_impact):'No direct impact')+'</div><p>Cash impact: '+money(s.cash_impact)+' · Profit impact: '+money(s.profit_impact)+' · Net debt impact: '+money(s.net_debt_impact)+'</p><p>'+esc((s.assumptions||[]).join(' '))+'</p></div>').join('');
const c=bp.cash_conversion_cycle||{};$('cccMetric').textContent=c.cash_conversion_cycle_days==null?'–':num(c.cash_conversion_cycle_days);$('workingCapital').innerHTML='<div class="grid4">'+[['DSO',c.dso_days],['DIO',c.dio_days],['DPO',c.dpo_days],['CCC',c.cash_conversion_cycle_days]].map(x=>metric(x[0],x[1]==null?'–':num(x[1])+' gün','')).join('')+'</div><div class="notice" style="margin-top:12px">'+esc(c.note||'')+'</div>'+(c.inventory_flag?'<div class="notice" style="margin-top:8px">'+esc(c.inventory_flag)+'</div>':'');
const ops=bp.opportunities||[];$('opportunities').innerHTML=ops.slice(0,6).map(o=>'<div class="scenario"><div class="small muted">#'+esc(o.rank)+' · '+esc(o.area)+'</div><h3>'+esc(o.title)+'</h3><div class="big">'+money(o.estimated_impact)+'</div><p>'+esc(o.calculation)+'</p><p>'+esc(o.assumption)+'</p></div>').join('');
const acts=bp.management_actions||[];$('actions').innerHTML=acts.map(a=>'<div class="actionRow"><div class="rank">'+a.priority+'</div><div><b>'+esc(a.action)+'</b><div class="small muted">'+esc(a.owner)+' · '+esc(a.time_horizon)+' · KPI: '+esc(a.kpi)+'</div></div><span class="tag '+esc(a.severity)+'">'+esc(a.severity)+'</span></div>').join('')||'<div class="notice">Aksiyon yok.</div>';
const bm=bp.benchmarking||{};$('benchmark').innerHTML='<div class="notice">Sektör: <b>'+esc(bm.sector)+'</b> · '+esc(bm.overall_label)+' · '+esc(bm.overall_score)+'/100</div><div class="tableWrap" style="margin-top:8px"><table><thead><tr><th>Gösterge</th><th>Değer</th><th>Bant</th><th>Favorability</th></tr></thead><tbody>'+(bm.metrics||[]).map(m=>'<tr><td>'+esc(m.label)+'</td><td>'+esc(m.value)+'</td><td>'+esc(m.band_low)+' / '+esc(m.band_mid)+' / '+esc(m.band_high)+'</td><td>'+esc(m.favorability)+'</td></tr>').join('')+'</tbody></table></div>';
const tr=bp.trend_analysis||{};$('trendBlock').innerHTML=tr.available?'<div class="notice">Dönemler: '+(tr.period_labels||[]).map(esc).join(' → ')+'</div><div class="tableWrap" style="margin-top:10px"><table><thead><tr><th>Metric</th><th>Series</th><th>Latest direction</th></tr></thead><tbody>'+Object.values(tr.metric_trends||{}).map(m=>'<tr><td>'+esc(m.label)+'</td><td>'+m.series.map(x=>x==null?'–':num(x)).join(' → ')+'</td><td>'+esc(m.latest_direction)+'</td></tr>').join('')+'</tbody></table></div>':'<div class="notice">'+esc(tr.reason||'Trend için 2+ dönem gerekir.')+'</div>';
const accounts=d.canonical_model?.accounts||[];$('trace').innerHTML='<div class="notice">Traceability: '+accounts.length+' canonical account rows. Örnek kaynaklar aşağıda.</div><table style="margin-top:8px"><thead><tr><th>Hesap</th><th>Ad</th><th>Bakiye</th><th>Sheet</th><th>Row</th></tr></thead><tbody>'+accounts.slice(0,15).map(a=>'<tr><td>'+esc(a.account_code)+'</td><td>'+esc(a.account_name)+'</td><td>'+money(a.balance)+'</td><td>'+esc(a.source_sheet)+'</td><td>'+esc(a.source_row)+'</td></tr>').join('')+'</tbody></table>';
$('plTable').innerHTML=table('Gelir Tablosu',pl);$('bsTable').innerHTML=table('Bilanço',bs);
}
function renderHub(ms){
  if(!ms){$('dataHubCard').classList.add('hidden');return}
  $('dataHubCard').classList.remove('hidden');
  const sm=ms.summary||{};
  const labels=[['Sales',sm.sales_loaded?'Loaded':'Not loaded',''],['AR Aging',sm.ar_aging_loaded?'Loaded':'Not loaded',''],['AP Aging',sm.ap_aging_loaded?'Loaded':'Not loaded',''],['Inventory',sm.inventory_loaded?'Loaded':'Not loaded','']];
  $('hubSummary').innerHTML=labels.map(x=>metric(x[0],x[1],x[2])).join('');
  const checks=ms.reconciliation?.checks||[];
  $('hubReconciliation').innerHTML='<div class="sectionHead"><div><h2>Source Reconciliation</h2><p>GL ile operasyonel dosya arasındaki farklar</p></div></div>'+(checks.length?'<div class="tableWrap"><table><thead><tr><th>Kontrol</th><th>GL</th><th>Source</th><th>Difference</th><th>Status</th></tr></thead><tbody>'+checks.map(c=>'<tr><td>'+esc(c.name)+'</td><td>'+money(c.gl_value)+'</td><td>'+money(c.source_value)+'</td><td>'+money(c.difference)+'</td><td>'+esc(c.status)+'</td></tr>').join('')+'</tbody></table></div>':'<div class="notice">Mutabakat için yeterli veri yok.</div>');
  const an=ms.analysis||{}; const sales=an.sales||{};
  $('salesIntel').innerHTML='<div class="sectionHead"><div><h2>Sales Intelligence</h2><p>Müşteri / ürün / ciro / vade fiyatlaması</p></div></div>'+(an.sales?'<div class="grid4">'+metric('Satış Tutarı',money(sales.net_sales),'Satış verisi')+metric('Peşin Fiyat',money(sales.cash_price_total),'Peşin toplam')+metric('Vadeli Fiyat',money(sales.term_price_total),'Vadeli toplam')+metric('Vade Primi',pct(sales.term_premium_pct),'Peşin → vadeli')+'</div><div class="grid4" style="margin-top:10px">'+metric('Müşteri',sales.customer_count??'–','')+metric('İlk 10 Müşteri Payı',pct(sales.top_10_customer_share_pct),'Concentration')+metric('Ödenen',money(sales.paid_total),'Kaynak kolonu')+metric('Açık Bakiye',money(sales.outstanding_total),'31.12.2019')+'</div>'+((sales.overdue_amount_by_status!=null)?'<div class="insight high" style="margin-top:10px"><b>Vadesi geçmiş bakiye</b><p>'+money(sales.overdue_amount_by_status)+' · '+(sales.overdue_row_count||0)+' satır</p></div>':'')+((sales.product_mix||[]).length?'<div class="insight" style="margin-top:10px"><b>Ürün karması</b><p>'+sales.product_mix.slice(0,7).map(v=>esc(v.name)+': '+money(v.sales)+' ('+pct(v.share_pct)+')').join(' · ')+'</p></div>':'')+(sales.findings||[]).map(f=>'<div class="insight '+esc(f.severity)+'" style="margin-top:10px"><b>'+esc(f.title)+'</b><p>'+esc(f.detail)+'</p></div>').join(''):'<div class="notice">Sales datası yüklenmedi.</div>');
  $('arApIntel').innerHTML='<div class="sectionHead"><div><h2>AR / AP Intelligence</h2><p>Aging, overdue ve operasyonel vade</p></div></div>'+(an.ar_aging?'<div class="insight"><b>AR Aging</b><p>Outstanding: '+money(an.ar_aging.outstanding)+' · Overdue: '+money(an.ar_aging.overdue)+' · Overdue %: '+pct(an.ar_aging.overdue_pct)+' · DSO: '+(an.ar_aging.dso_days==null?'–':num(an.ar_aging.dso_days)+' gün')+'</p></div>':'<div class="notice">AR aging yüklenmedi.</div>')+(an.ap_aging?'<div class="insight" style="margin-top:10px"><b>AP Aging</b><p>Outstanding: '+money(an.ap_aging.outstanding)+' · Overdue: '+money(an.ap_aging.overdue)+' · Overdue %: '+pct(an.ap_aging.overdue_pct)+' · DPO: '+(an.ap_aging.dpo_days==null?'–':num(an.ap_aging.dpo_days)+' gün')+'</p></div>':'<div class="notice" style="margin-top:10px">AP aging yüklenmedi.</div>');
  const inv=an.inventory||{}; $('inventoryIntel').innerHTML='<div class="sectionHead"><div><h2>Inventory Intelligence</h2><p>Stok değeri ve yaşlanma sinyalleri</p></div></div>'+(an.inventory?'<div class="grid4">'+metric('Inventory Value',money(inv.value),'Inventory Data')+metric('SKU Count',inv.sku_count??'–','')+metric('DIO',inv.dio_days==null?'–':num(inv.dio_days)+' gün','')+metric('180+ Days',money(inv.stale_180_amount),'Stale stock')+'</div>'+(inv.findings||[]).map(f=>'<div class="insight '+esc(f.severity)+'" style="margin-top:10px"><b>'+esc(f.title)+'</b><p>'+esc(f.detail)+'</p></div>').join(''):'<div class="notice">Inventory datası yüklenmedi.</div>');
}
async function run(url,fd,kind='single'){$('error').classList.add('hidden');$('analyze').disabled=true;$('analyzeTrend').disabled=true;$('analyzeHub').disabled=true;try{const r=await fetch(url,{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Analiz başarısız');render(d);if(kind==='hub')renderHub(d.data_hub)}catch(e){$('error').textContent=e.message;$('error').classList.remove('hidden')}finally{$('analyze').disabled=false;$('analyzeTrend').disabled=false;$('analyzeHub').disabled=false}}
$('analyze').onclick=()=>{const f=$('file').files[0];if(!f){$('error').textContent='Önce bir finansal dosya seç.';$('error').classList.remove('hidden');return}const fd=new FormData();fd.append('file',f);if($('sector').value)fd.append('sector',$('sector').value);run('/api/mizan/analyze',fd)};
$('analyzeTrend').onclick=()=>{const fs=[...$('trendFiles').files];if(fs.length<2){$('error').textContent='Trend analizi için en az 2 dönem seç.';$('error').classList.remove('hidden');return}const fd=new FormData();fs.forEach(f=>fd.append('files',f));if($('trendSector').value)fd.append('sector',$('trendSector').value);run('/api/mizan/analyze-trend',fd,'trend')};
$('analyzeHub').onclick=()=>{const fs=[...$('hubFiles').files];if(fs.length<1){$('error').textContent='Data Hub için en az bir dosya seçin. Mizan olmadan da satış / AR / AP / stok verisi analiz edilebilir.';$('error').classList.remove('hidden');return}const fd=new FormData();fs.forEach(f=>fd.append('files',f));if($('hubSector').value)fd.append('sector',$('hubSector').value);run('/api/data-hub/analyze',fd,'hub')};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabPanel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(t.dataset.tab).classList.add('active')});
$('printBtn').onclick=()=>window.print();$('jsonBtn').onclick=()=>{if(!LAST)return;const blob=new Blob([JSON.stringify(LAST,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='finance_bp_analysis.json';a.click();URL.revokeObjectURL(a.href)};
$('aiBtn').onclick=async()=>{if(!LAST)return;$('aiBox').classList.remove('hidden');$('aiBox').textContent='AI CFO yorumu hazırlanıyor...';try{const r=await fetch('/api/ai/cfo-narrative',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysis:LAST})});const d=await r.json();if(!d.available){$('aiBox').textContent=d.reason||'AI yapılandırılmamış.';return}const x=d.response||{};$('aiBox').innerHTML='<b>AI CFO View</b><p>'+esc(x.executive_message||'')+'</p>'+((x.key_risks||[]).map(v=>'<div>• '+esc(v)+'</div>').join(''))+((x.actions||[]).map(v=>'<div>→ '+esc(v)+'</div>').join(''))+'<div class="small muted" style="margin-top:8px">Model: '+esc(d.model)+'</div>'}catch(e){$('aiBox').textContent='AI isteği başarısız: '+e.message}};
async function loadConfig(){try{const r=await fetch('/api/config');const d=await r.json();[[$('sector'),d.sectors],[$('trendSector'),d.sectors],[$('hubSector'),d.sectors]].forEach(([sel,list])=>list.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;sel.appendChild(o)}))}catch(e){}}
loadConfig();
